const ACTION_TYPES = {
    LOAD_MOVIES: 'LOAD_MOVIES',
    LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
    LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
    SEARCH_BY: 'SEARCH_BY',
    SORT_MOVIES: 'SORT_MOVIES',
    PERSIST_LAST_SEARCH_PHRASE: 'PERSIST_LAST_SEARCH_PHRASE',
    SEARCH_MOVIE_CHANGE: 'SEARCH_MOVIE_CHANGE',
    SELECT_MOVIE: 'SELECT_MOVIE',
    LOAD_MOVIE_DETAILS_SUCCESS: 'LOAD_MOVIE_DETAILS_SUCCESS',
    LOAD_MOVIES_SIMILAR_GENRE: 'LOAD_MOVIES_SIMILAR_GENRE',
    IS_LOADING: 'IS_LOADING',
    SET_MODE: 'SET_MODE',
}

export default ACTION_TYPES
