const CONSTANTS = {
    NO_FILMS_FOUND: 'No Films found',
    ERROR: 'Error occurred while fetching the data!',
    NETFLIX: 'netflixroulette',
    FIND: 'FIND YOUR MOVIE',
    SEARCH_BY: 'SEARCH BY',
    TITLE: 'TITLE',
    GENRE: 'GENRE',
    SEARCH: 'SEARCH',
    MOVIES_FOUND: 'movies found',
    RATING: 'RATING',
    RELEASE: 'RELEASE DATE',
    SORT: 'SORT BY',
    EDIT: 'Edit',
    DELETE: 'Delete',
    ADD_MOVIE: '+ADD MOVIE',
    RESET: 'RESET',
    SUBMIT: 'SUBMIT',
    ADD_MOVIE_TITLE: 'ADD MOVIE',
    EDIT_MOVIE_TITLE: 'EDIT MOVIE',
    RESULTS_FOR: 'RESULTS FOR',
    baseURL: 'http://react-cdp-api.herokuapp.com/movies',
}

export default CONSTANTS
